# Generated by Django 3.0 on 2019-12-04 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('shop_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nothing', max_length=200, null=True)),
                ('product_type', models.CharField(default='Nothing', max_length=200, null=True)),
                ('size', models.CharField(default='Nothing', max_length=200, null=True)),
                ('color', models.CharField(default='Nothing', max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, default='Nothing', null=True)),
                ('address', models.TextField(blank=True, default='Nothing', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clory_data.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clory_data.Product')),
            ],
        ),
    ]
